spring:
  application:
    name: Agenda API
  datasource:
    url: jdbc:h2:mem:agenda
    username: sa
    password: teste
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console